// <auto-generated />
using System;
using Cediva.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cediva.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816223441_AgregarEntidadesLogistica")]
    partial class AgregarEntidadesLogistica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cediva.Domain.Agregados.Despacho.Despacho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Despachos", (string)null);
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Despacho.ItemDespacho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DespachoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DespachoId");

                    b.ToTable("ItemDespachos", (string)null);
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Inventario.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Inventarios", (string)null);
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Inventario.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("Cediva.Dominio.Agregados.Producto.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaPadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Cediva.Dominio.Agregados.Producto.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("Cediva.Dominio.Agregados.Producto.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MarcaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PuntoReorden")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("MarcaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Despacho.Despacho", b =>
                {
                    b.OwnsOne("Cediva.Dominio.ObjetosValor.Direccion", "DireccionEntrega", b1 =>
                        {
                            b1.Property<Guid>("DespachoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Direccion_Calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Direccion_Ciudad");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Direccion_CodigoPostal");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Direccion_Complemento");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Direccion_Departamento");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Direccion_Numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Direccion_Pais");

                            b1.HasKey("DespachoId");

                            b1.ToTable("Despachos");

                            b1.WithOwner()
                                .HasForeignKey("DespachoId");
                        });

                    b.Navigation("DireccionEntrega")
                        .IsRequired();
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Despacho.ItemDespacho", b =>
                {
                    b.HasOne("Cediva.Domain.Agregados.Despacho.Despacho", null)
                        .WithMany("Items")
                        .HasForeignKey("DespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Cediva.Dominio.ObjetosValor.Cantidad", "Cantidad", b1 =>
                        {
                            b1.Property<Guid>("ItemDespachoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Cantidad_Unidad");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Cantidad_Valor");

                            b1.HasKey("ItemDespachoId");

                            b1.ToTable("ItemDespachos");

                            b1.WithOwner()
                                .HasForeignKey("ItemDespachoId");
                        });

                    b.Navigation("Cantidad")
                        .IsRequired();
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Inventario.Inventario", b =>
                {
                    b.OwnsOne("Cediva.Dominio.ObjetosValor.Cantidad", "CantidadDisponible", b1 =>
                        {
                            b1.Property<Guid>("InventarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Cantidad_Unidad");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Cantidad_Valor");

                            b1.HasKey("InventarioId");

                            b1.ToTable("Inventarios");

                            b1.WithOwner()
                                .HasForeignKey("InventarioId");
                        });

                    b.Navigation("CantidadDisponible")
                        .IsRequired();
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Inventario.Movimiento", b =>
                {
                    b.HasOne("Cediva.Domain.Agregados.Inventario.Inventario", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Cediva.Dominio.ObjetosValor.Cantidad", "Cantidad", b1 =>
                        {
                            b1.Property<Guid>("MovimientoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Cantidad_Unidad");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Cantidad_Valor");

                            b1.HasKey("MovimientoId");

                            b1.ToTable("Movimientos");

                            b1.WithOwner()
                                .HasForeignKey("MovimientoId");
                        });

                    b.Navigation("Cantidad")
                        .IsRequired();
                });

            modelBuilder.Entity("Cediva.Dominio.Agregados.Producto.Categoria", b =>
                {
                    b.HasOne("Cediva.Dominio.Agregados.Producto.Categoria", "CategoriaPadre")
                        .WithMany()
                        .HasForeignKey("CategoriaPadreId");

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("Cediva.Dominio.Agregados.Producto.Producto", b =>
                {
                    b.HasOne("Cediva.Dominio.Agregados.Producto.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cediva.Dominio.Agregados.Producto.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Despacho.Despacho", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cediva.Domain.Agregados.Inventario.Inventario", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
